version: "3.9"

services:
  app:
    build:
      context: . # Building the Dockerfile within the current directory
      args:
        - DEV=true
    ports:
      - "8000:8000" # Local machine port : Container port
    volumes:
      # Updates made to the code will automatically be reflected in the running container
      # so that every line of code modified is automatically synced to the code running in the container
      - ./app:/app
      - static-db-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db # Using the name of the DB service as the hostname
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=devpassword
    depends_on:
      - db
  db:
    image: postgres:13-alpine # Docs: https://hub.docker.com/_/postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment: # Credentials for local development and testing
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword

volumes:
  db-data:
  static-db-data:
