version: "3.9"

services:
  app:
    build:
      context: . # Use dockerfile in the current location
    restart: always # Restart automatically if the app crashes
    volumes:
      - static-data:/vol/web # Volume to serve static data through Nginx proxy
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db # db should start first

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  proxy:
    build:
      context: ./proxy # Build the image for this service from ./proxy
    restart: always
    depends_on:
      - app # Start the app first
    ports:
      - "80:8000"
    volumes:
      - static-data:/vol/static

volumes:
  db-data:
  static-data:
