---
name: Checks

on: [ push ] # Actions running on git push

jobs: # List of jobs to run on git push
  test-lint: # Defining job called test-lint
    name: Test and lint
    # See runners at https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-20.04 # Runner (OS) that the job will be running on
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3 # Checks out the code inside the Actions job (by default the code is not checked out in the job)
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
